# -*- coding: utf-8 -*-
"""Empresas unicórnios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/137gjfv2bsxRq3ehOcJzFkx2qvQkFVAxB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

#Ler os dados
base_dados=pd.read_csv('Startups in 2021 end.csv')
#Dimensão
base_dados.shape

#Primeiro registro
base_dados.head()

#Colunas
base_dados.columns

#Renomear
base_dados.rename( columns={
    'Unnamed: 0' : 'Id',
    'Company' : 'Empresa',
    'Valuation ($B)' : 'Valor ($)',
    'Date Joined' : 'Data de Adesão',
    'Country' : 'Pais',
    'City' : 'Cidade',
    'Industry': 'Setor',
    'Select Investors': 'Investidores',
}, inplace=True )

#Verificar informação
base_dados.info()

#Campos nulos
base_dados.isnull().sum()

#Gráfico
plt.figure(figsize=(15,6) )
plt.title('Analisando Campos Nulos')
sns.heatmap(base_dados.isnull()) #campos nulos na base de dados

#Campos únicos
base_dados.nunique()

#Valores únicos
base_dados['Setor'].unique()

#Valores únicos - rank
base_dados['Setor'].value_counts()

base_dados['Setor'].value_counts(normalize=True)

plt.figure( figsize=(15,6) )
plt.title('Analise dos Setores')
plt.bar( Base_Dados['Setor'].value_counts().index, Base_Dados['Setor'].value_counts())
plt.xticks( rotation=45, ha='right' );

base_dados['Pais'].value_counts()

analise=round(base_dados['Pais'].value_counts(normalize=True)*100, 1)

#Gráfico geral dos países
plt.figure(figsize=(15,6))
plt.title('Analise dos Países geradores de Unicoórnios')
plt.pie(
    analise,
    labels= analise.index,
    shadow=True,
    startangle=90,
    autopct='%1.1f%%'
);

plt.figure(figsize=(15,6))
plt.title('Analise dos Países gerador de Unicórnios - Top 10')
plt.pie(
    analise.head(10),
    labels = analise.index[0:10],
    shadow=True,
    startangle=90,
    autopct='%1.1f%%'
);

analise.head(10)

#Conversão para data
base_dados['Data de Adesão']= pd.to_datetime(base_dados['Data de Adesão'])
base_dados['Data de Adesão'].head()

#Extrair dados
base_dados['Mês'] = pd.DatetimeIndex(base_dados['Data de Adesão']).month
base_dados['Ano'] = pd.DatetimeIndex(base_dados['Data de Adesão']).year
base_dados.head()

#Tabela analítica
analise_agrupada = base_dados.groupby(by=['Pais', 'Ano', 'Mês', 'Empresa'] ).count()['Id'].reset_index()
analise_agrupada

analise_agrupada.loc[
  analise_agrupada['Pais'] == 'Brazil'
]

# Transformando a coluna Valor
base_dados['Valor ($)'].apply( lambda Linha: Linha.replace('$', '') )

# Transformando a coluna Valor
base_dados['Valor ($)'] = pd.to_numeric(base_dados['Valor ($)'].apply( lambda Linha: Linha.replace('$', '') ) )
base_dados.head()

#Quanto o setor de fintech vale
# E quanto os países do top 5 tem de evaluation
base_dados.groupby(by=['Pais', 'Setor']).sum()['Valor ($)'].reset_index()

analise_pais = base_dados.groupby(by=['Pais']).sum()['Valor ($)'].reset_index()
analise_pais.sort_values('Valor ($)')

analise_valor = analise_pais.sort_values('Valor ($)', ascending=False)
analise_valor.head()

analise_valor = analise_pais.sort_values('Valor ($)')
analise_valor.head()

plt.figure( figsize=(15,6) )
plt.plot(analise_valor['Pais'], analise_valor['Valor ($)'] )
plt.title('Analise do Valor por Pais')
plt.xticks( rotation=45, ha='right');